// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhweczutxgpathsazuhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlod2VjenV0eGdwYXRoc2F6dWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzU0NTMsImV4cCI6MjA3MTk1MTQ1M30.6XKTMhtEsEXGaHfesIM7eO14KRZnpnFx3kaGSNna-L4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});